package com.mapbox.mapboxgoshare.util;

public class LayerIdConstants {
  public static final String SELECTED_LOCK_STATION_SYMBOL_LAYER_ID = "SELECTED_LOCK_STATION_SYMBOL_LAYER_ID";
  public static final String MOPED_GARAGE_LOCATION_SYMBOL_LAYER_ID = "MOPED_GARAGE_LOCATION_SYMBOL_LAYER_ID";
  public static final String INDIVIDUAL_BIKE_SYMBOL_LAYER_ID = "INDIVIDUAL_BIKE_SYMBOL_LAYER_ID";
  public static final String INDIVIDUAL_SCOOTER_SYMBOL_LAYER_ID = "INDIVIDUAL_SCOOTER_SYMBOL_LAYER_ID";
  public static final String NO_PARK_ZONE_FILL_LAYER_ID = "NO_PARK_ZONE_FILL_LAYER_ID";
  public static final String PREFERRED_PARKING_ZONE_FILL_LAYER_ID = "PREFERRED_PARKING_ZONE_FILL_LAYER_ID";
  public static final String NEIGHBORHOOD_PARKING_ZONE_FILL_LAYER_ID = "NEIGHBORHOOD_PARKING_ZONE_FILL_LAYER_ID";
  public static final String NEIGHBORHOOD_PARKING_ZONE_LINE_LAYER_ID = "NEIGHBORHOOD_PARKING_ZONE_LINE_LAYER_ID";
  public static final String HEATMAP_LAYER_ID = "HEATMAP_LAYER_ID";
  public static final String CLUSTER_COUNT_SYMBOL_LAYER_ID = "CLUSTER_COUNT_SYMBOL_LAYER_ID";
  public static final String WALK_TO_VEHICLE_ROUTE_LINE_LAYER_ID = "WALK_TO_VEHICLE_ROUTE_LINE_LAYER_ID";
  public static final String PLACES_PLUGIN_SEARCH_RESULT_SYMBOL_LAYER_ID = "PLACES_PLUGIN_SEARCH_RESULT_SYMBOL_LAYER_ID";
}
