package com.mapbox.mapboxgoshare.util;

public class SourceIdConstants {

  public static final String SELECTED_LOCK_STATION_SOURCE_ID = "SELECTED_LOCK_STATION_SOURCE_ID";
  public static final String WALK_TO_VEHICLE_ROUTE_SOURCE_ID = "WALK_TO_VEHICLE_ROUTE_SOURCE_ID";
  public static final String MOPED_GARAGE_SOURCE_ID = "MOPED_GARAGE_SOURCE_ID";
  public static final String INDIVIDUAL_BIKE_SOURCE_ID = "INDIVIDUAL_BIKE_SOURCE_ID";
  public static final String INDIVIDUAL_SCOOTER_SOURCE_ID = "INDIVIDUAL_SCOOTER_SOURCE_ID";
  public static final String INDIVIDUAL_SCOOTER_CLUSTER_SOURCE_ID = "INDIVIDUAL_SCOOTER_CLUSTER_SOURCE_ID";
  public static final String INDIVIDUAL_BIKE_GEOJSON_CLUSTER_SOURCE_ID = "INDIVIDUAL_BIKE_GEOJSON_CLUSTER_SOURCE_ID";
  public static final String NO_PARK_ZONE_SOURCE_ID = "NO_PARK_ZONE_SOURCE_ID";
  public static final String PREFERRED_PARKING_ZONE_SOURCE_ID = "PREFERRED_PARKING_ZONE_SOURCE_ID";
  public static final String NEIGHBORHOOD_PARK_ZONE_SOURCE_ID = "NEIGHBORHOOD_PARK_ZONE_SOURCE_ID";
  public static final String HEATMAP_SOURCE_ID = "HEATMAP_SOURCE_ID";
  public static final String PLACES_PLUGIN_SEARCH_RESULT_SOURCE_ID = "PLACES_PLUGIN_SEARCH_RESULT_SOURCE_ID";

}
